spring:
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: ${smtp_user}
    password: ${smtp_pass}

    properties:
      mail:
        smtp:
          auth: true
          startls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8081